### ISSUE TITLE
Plantilla para creación de rol de despliegue con identity provider

### ISSUE THREAD

**Issue by cbrunosps** [spsdevops/aws_sam_github_quickstart_template#35]
El objetivo es crear una plantilla de Cloudformation la cual cree:
1. Identity provider
2. Rol de despliegue
3. Permisos para rol de despliegue

Además, habría que parametrizarlo para que reciba el repositorio al cual se le dará autorización para desplegar en esta cuenta.

**Comment by rortega-sps** [comment]
Esto ya lo atendió @acifuentesps en el commit fdd23cd34d220012cb68303b5bd7690f607dd26b. 

Pero me parece que se debe regresar la política para el Linked Role, que se eliminó acá c6546d9a2014d755d605605d7397277cd0421b16. No se está creando en Linked Role en esta plantilla (la del rol), sino que le está dando permisos a Github de crearlo si no existe (cuando despliegue la plantilla del proyecto).

Como algunos nunca han usado el servicio de API Gateway probablemente falle el despliegue, pero se puede probar borrando el linked role y lanzando el despliegue desde un repo par ver si falla.

@acifuentesps puede ir haciendo esta prueba o lo revisamos en la sesión.

**Comment by rortega-sps** [comment]
No es necesario el Service Linked Role
